[accounts.deployer]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon"
balance = 100_000_000_000_000

[accounts.wallet_1]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
balance = 100_000_000_000_000

[accounts.wallet_2]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon ability"
balance = 100_000_000_000_000

[accounts.wallet_3]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon acid"
balance = 100_000_000_000_000

[accounts.wallet_4]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon acoustic"
balance = 100_000_000_000_000

[accounts.wallet_5]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon across"
balance = 100_000_000_000_000
